"""Add stk_phone to payment_request

Revision ID: 2596a51cb5e4
Revises: 
Create Date: 2025-07-22 21:35:07.884563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2596a51cb5e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stk_phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_column('stk_phone')

    # ### end Alembic commands ###
