"""Make stk_phone NOT NULL

Revision ID: 5a081fe43cb3
Revises: 71b463218d84
Create Date: 2025-07-24 01:31:37.586257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a081fe43cb3'
down_revision = '71b463218d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('stk_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.alter_column('stk_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
